# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'WarmUpKitMobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'SnapKit', '~> 5.0.0'
    pod 'Charts'

  # Pods for WarmUpKitMobile

end

target 'WarmUpKitMobile WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WarmUpKitMobile WatchKit App

end

target 'WarmUpKitMobile WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WarmUpKitMobile WatchKit Extension

end
